GRANT USAGE ON SCHEMA moodleNati TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA moodleNati TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA moodleNati TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA moodleNati TO "apps";
