GRANT USAGE ON SCHEMA moodle TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA moodle TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA moodle TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA moodle TO "apps";