insert into moodle.levels (label) VALUES('2de générale et technologique');
insert into moodle.levels (label) VALUES('2de professionnelle');
insert into moodle.levels (label) VALUES('1re générale et technologique');
insert into moodle.levels (label) VALUES('1re professionnelle');
insert into moodle.levels (label) VALUES('terminale générale et technologique');
insert into moodle.levels (label) VALUES('terminale professionnelle');
insert into moodle.levels (label) VALUES('voie BEP');
insert into moodle.levels (label) VALUES('voie BMA');
insert into moodle.levels (label) VALUES('voie BP');
insert into moodle.levels (label) VALUES('voie BT');
insert into moodle.levels (label) VALUES('voie BTM');
insert into moodle.levels (label) VALUES('voie CAP');
insert into moodle.levels (label) VALUES('voie FC');
insert into moodle.levels (label) VALUES('voie MC');

insert into moodle.disciplines (label) VALUES('activités pluridisciplinaires');
insert into moodle.disciplines (label) VALUES('agroéquipements');
insert into moodle.disciplines (label) VALUES('agronomie');
insert into moodle.disciplines (label) VALUES('aide individuelle en français');
insert into moodle.disciplines (label) VALUES('aide individuelle en mathématiques');
insert into moodle.disciplines (label) VALUES('aménagement paysager');
insert into moodle.disciplines (label) VALUES('aménagements des espaces naturels');
insert into moodle.disciplines (label) VALUES('animalerie');
insert into moodle.disciplines (label) VALUES('aquaculture');
insert into moodle.disciplines (label) VALUES('arts');
insert into moodle.disciplines (label) VALUES('biochimie');
insert into moodle.disciplines (label) VALUES('biochimie-microbiologie-biotechnologie');
insert into moodle.disciplines (label) VALUES('biochimie-microbiologie');
insert into moodle.disciplines (label) VALUES('biologie animale');
insert into moodle.disciplines (label) VALUES('biologie-écologie');
insert into moodle.disciplines (label) VALUES('biologie');
insert into moodle.disciplines (label) VALUES('biologie végétale');
insert into moodle.disciplines (label) VALUES('chimie');
insert into moodle.disciplines (label) VALUES('comptabilité-bureautique');
insert into moodle.disciplines (label) VALUES('documentation');
insert into moodle.disciplines (label) VALUES('écologie, agronomie, territoire et développement durable');
insert into moodle.disciplines (label) VALUES('écologie');
insert into moodle.disciplines (label) VALUES('économie d''entreprise');
insert into moodle.disciplines (label) VALUES('économie-droit');
insert into moodle.disciplines (label) VALUES('économie sociale et familiale');
insert into moodle.disciplines (label) VALUES('éducation civique, juridique et sociale');
insert into moodle.disciplines (label) VALUES('éducation socioculturelle');
insert into moodle.disciplines (label) VALUES('enseignement technologique et professionnel');
insert into moodle.disciplines (label) VALUES('E.P.S.');
insert into moodle.disciplines (label) VALUES('équipements agroalimentaires');
insert into moodle.disciplines (label) VALUES('équipements hydrauliques');
insert into moodle.disciplines (label) VALUES('équitation');
insert into moodle.disciplines (label) VALUES('français-documentation');
insert into moodle.disciplines (label) VALUES('français');
insert into moodle.disciplines (label) VALUES('français-philosophie');
insert into moodle.disciplines (label) VALUES('génie alimentaire');
insert into moodle.disciplines (label) VALUES('génie des procédés (IAA)');
insert into moodle.disciplines (label) VALUES('génie industriel');
insert into moodle.disciplines (label) VALUES('géographie');
insert into moodle.disciplines (label) VALUES('gestion');
insert into moodle.disciplines (label) VALUES('grec');
insert into moodle.disciplines (label) VALUES('heures de vie de classe');
insert into moodle.disciplines (label) VALUES('hippologie-équitation');
insert into moodle.disciplines (label) VALUES('hippologie');
insert into moodle.disciplines (label) VALUES('histoire-géographie-éducation civique');
insert into moodle.disciplines (label) VALUES('histoire-géographie');
insert into moodle.disciplines (label) VALUES('histoire, géographie, instruction civique');
insert into moodle.disciplines (label) VALUES('hygiène-prévention-secourisme');
insert into moodle.disciplines (label) VALUES('informatique');
insert into moodle.disciplines (label) VALUES('langues vivantes de l''enseignement agricole');
insert into moodle.disciplines (label) VALUES('latin');
insert into moodle.disciplines (label) VALUES('machinisme');
insert into moodle.disciplines (label) VALUES('maréchalerie');
insert into moodle.disciplines (label) VALUES('mathématiques');
insert into moodle.disciplines (label) VALUES('mathématiques-informatique');
insert into moodle.disciplines (label) VALUES('mercatique');
insert into moodle.disciplines (label) VALUES('microbiologie');
insert into moodle.disciplines (label) VALUES('œnologie');
insert into moodle.disciplines (label) VALUES('philosophie');
insert into moodle.disciplines (label) VALUES('physique appliquée');
insert into moodle.disciplines (label) VALUES('physique-chimie');
insert into moodle.disciplines (label) VALUES('physique');
insert into moodle.disciplines (label) VALUES('pratiques professionnelles');
insert into moodle.disciplines (label) VALUES('pratiques sociales et culturelles');
insert into moodle.disciplines (label) VALUES('prévention santé environnementale');
insert into moodle.disciplines (label) VALUES('productions animales');
insert into moodle.disciplines (label) VALUES('productions horticoles');
insert into moodle.disciplines (label) VALUES('productions végétales');
insert into moodle.disciplines (label) VALUES('projet professionnel');
insert into moodle.disciplines (label) VALUES('sciences économiques et humaines');
insert into moodle.disciplines (label) VALUES('sciences économiques et sociales, gestion');
insert into moodle.disciplines (label) VALUES('sciences économiques et sociales');
insert into moodle.disciplines (label) VALUES('sciences économiques');
insert into moodle.disciplines (label) VALUES('sciences et techniques aquacoles');
insert into moodle.disciplines (label) VALUES('sciences et techniques des agroéquipements');
insert into moodle.disciplines (label) VALUES('sciences et techniques horticoles');
insert into moodle.disciplines (label) VALUES('sciences et techniques');
insert into moodle.disciplines (label) VALUES('sciences et technologie des équipements');
insert into moodle.disciplines (label) VALUES('secrétariat-bureautique');
insert into moodle.disciplines (label) VALUES('statistiques');
insert into moodle.disciplines (label) VALUES('SVT');
insert into moodle.disciplines (label) VALUES('techniques animalières');
insert into moodle.disciplines (label) VALUES('techniques commerciales');
insert into moodle.disciplines (label) VALUES('techniques de communication');
insert into moodle.disciplines (label) VALUES('techniques de documentation');
insert into moodle.disciplines (label) VALUES('techniques économiques');
insert into moodle.disciplines (label) VALUES('techniques forestières');
insert into moodle.disciplines (label) VALUES('technologie aquacole');
insert into moodle.disciplines (label) VALUES('technologie informatique et de communication');
insert into moodle.disciplines (label) VALUES('tourisme innovation management (TIM)');
insert into moodle.disciplines (label) VALUES('viticulture');
insert into moodle.disciplines (label) VALUES('viticulture-œnologie');
insert into moodle.disciplines (label) VALUES('zootechnie-hippologie');
insert into moodle.disciplines (label) VALUES('zootechnie');